//
//  PersonalizedInsight.swift
//  Lumen
//
//  Personalized AI-powered skincare insight generated by Bedrock multi-agent system
//

import Foundation

/// Represents a personalized daily insight generated by the multi-agent AI system
struct PersonalizedInsight: Codable, Identifiable, Sendable {
    let id: String
    let userId: String
    let generatedAt: Date
    let dailyTip: String
    let checkInQuestion: String?
    let progressPrediction: String?
    let environmentalRecommendation: String?
    let recommendedProducts: [Product]?
    let latestScanSummary: ScanSummary?

    enum CodingKeys: String, CodingKey {
        case id = "insight_id"
        case userId = "user_id"
        case generatedAt = "generated_at"
        case dailyTip = "daily_tip"
        case checkInQuestion = "check_in_question"
        case progressPrediction = "progress_prediction"
        case environmentalRecommendation = "environmental_recommendation"
        case recommendedProducts = "recommended_products"
        case latestScanSummary = "latest_scan_summary"
    }

    /// Summary of the latest scan that triggered this insight
    struct ScanSummary: Codable, Sendable {
        let condition: String
        let timestamp: Int?
        let analysisId: String?
        let confidence: Double?

        enum CodingKeys: String, CodingKey {
            case condition
            case timestamp
            case analysisId = "analysis_id"
            case confidence
        }

        var date: Date? {
            guard let timestamp = timestamp else { return nil }
            return Date(timeIntervalSince1970: TimeInterval(timestamp))
        }
    }

    /// Product recommendation
    struct Product: Codable, Identifiable, Sendable {
        let id: String
        let name: String
        let brand: String
        let targetConditions: [String]?  // Optional - not always included in daily insights
        let price: String?
        let imageUrl: String?
        let description: String?  // Product description

        enum CodingKeys: String, CodingKey {
            case id = "product_id"
            case name
            case brand
            case targetConditions = "target_conditions"
            case price = "price_range"  // Map to price_range from Lambda
            case imageUrl = "amazon_url"  // Map to amazon_url from Lambda
            case description
        }
    }
}

/// Response from the personalized insights generator Lambda
struct PersonalizedInsightResponse: Codable, Sendable {
    let success: Bool
    let data: PersonalizedInsight?
    let error: String?
}

extension PersonalizedInsight {
    /// Check if this insight is recent (generated today)
    var isRecent: Bool {
        Calendar.current.isDateInToday(generatedAt)
    }

    /// Formatted generation time (e.g., "2 hours ago")
    var timeAgo: String {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .full
        return formatter.localizedString(for: generatedAt, relativeTo: Date())
    }

    /// Check if there are environmental factors to consider
    var hasEnvironmentalAlert: Bool {
        environmentalRecommendation != nil && !environmentalRecommendation!.isEmpty
    }

    /// Get priority level for environmental alert
    var environmentalPriority: String {
        guard let env = environmentalRecommendation?.lowercased() else { return "LOW" }

        if env.contains("high uv") || env.contains("extreme") {
            return "HIGH"
        } else if env.contains("low humidity") || env.contains("hot weather") {
            return "MEDIUM"
        }
        return "LOW"
    }
}
