//
//  Product.swift
//  Lumen
//
//  Product model for skincare product recommendations
//

import Foundation

struct Product: Codable, Identifiable, Equatable {
    let id: String
    let name: String
    let brand: String
    let category: String
    let description: String
    let targetConditions: [String]
    let ingredients: [String]
    let priceRange: String
    let amazonURL: String
    let rating: Double
    let reviewCount: Int
    
    /// Vector embedding for semantic search (mock - in production would come from embedding model)
    /// Not codable - computed from product features
    var embedding: [Double] {
        // In production, this would be a real embedding from a model like text-embedding-3-small
        // For now, we'll compute a simple mock embedding based on product features
        return computeMockEmbedding()
    }
    
    private func computeMockEmbedding() -> [Double] {
        // Mock 384-dimensional embedding (typical size for sentence transformers)
        // In reality, this would be generated by an embedding model
        var embedding = [Double](repeating: 0.0, count: 384)
        
        // Simple hash-based mock embedding for demonstration
        let seed = (name + brand + category).hash
        for i in 0..<384 {
            embedding[i] = Double((seed &+ i) % 100) / 100.0
        }
        
        return embedding
    }
    
    /// Calculate cosine similarity with another embedding
    static func cosineSimilarity(_ embedding1: [Double], _ embedding2: [Double]) -> Double {
        guard embedding1.count == embedding2.count else { return 0.0 }
        
        var dotProduct = 0.0
        var magnitude1 = 0.0
        var magnitude2 = 0.0
        
        for i in 0..<embedding1.count {
            dotProduct += embedding1[i] * embedding2[i]
            magnitude1 += embedding1[i] * embedding1[i]
            magnitude2 += embedding2[i] * embedding2[i]
        }
        
        let denominator = sqrt(magnitude1) * sqrt(magnitude2)
        return denominator > 0 ? dotProduct / denominator : 0.0
    }
}

